with testing

diff --git a/.github/workflows/01build.yml b/.github/workflows/01build.yml
--- a/.github/workflows/01build.yml
+++ b/.github/workflows/01build.yml
@@ -24,7 +24,21 @@ jobs:
           . venv/bin/activate
           pip install -r requirements.txt
 
-      - name: Build application
+      - name: Run application
         run: |
           . venv/bin/activate
-          python run.py build
+          nohup python run.py &
+
+      - name: Wait for the application to start
+        run: |
+          sleep 10  # Adjust this sleep time as needed
+
+      - name: Ping the application
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
+          if [ "$RESPONSE" -eq 200 ]; then
+            echo "successful"
+          else
+            echo "failed"
+            exit 1
+          fi
